sebastianbergmann/phpunit-documentation-french

- src/extending-phpunit.rst
- src/other-uses-for-tests.rst
- src/test-doubles.rst
> Replacing "simulacre" by mock

- src/annotations.rst
- src/assertions.rst
- src/database.rst
- src/incomplete-and-skipped-tests.rst
- src/risky-tests.rst
- src/test-doubles.rst
- src/textui.rst
- src/writing-tests-for-phpunit.rst
https://github.com/sebastianbergmann/phpunit-documentation-english/commit/41eb98187bc8b000b9057b4a32a6131d3a3984db
> Sync with 41eb981

- src/textui.rst
https://github.com/sebastianbergmann/phpunit-documentation-english/commit/84027c8754660ed121a5d90c93986cc54ee364ac
> Sync with 84027c8

- src/assertions.rst
https://github.com/sebastianbergmann/phpunit-documentation-english/commit/52bb5e270150166a397f54ed9546e4e77a1c8498
> Sync with 52bb5e2

- README.md
correction de la hiérarchie des titres
> fixed README title

- src/writing-tests-for-phpunit.rst
https://github.com/sebastianbergmann/phpunit-documentation-english/commit/8dd236b
> Sync with 8dd236b

- src/assertions.rst
- src/code-coverage-analysis.rst
- src/configuration.rst
- src/database.rst
- src/extending-phpunit.rst
- src/incomplete-and-skipped-tests.rst
- src/logging.rst
- src/test-doubles.rst
- src/textui.rst
https://github.com/sebastianbergmann/phpunit-documentation-english/pull/26
> sync with 38d351a

- src/database.rst
- src/writing-tests-for-phpunit.rst
Sync with : 
- [1cbe671 - Cleanup](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/1cbe6711b4dbd382f418067b2b4408ee864a723e)
- [ 90f051c - Fix](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/90f051c7f8fb0bbaed74a596749681a0ac06546e)
> Sync with 90f051c  and  1cbe671

- src/textui.rst
https://github.com/sebastianbergmann/phpunit-documentation-english/commit/ca9e5b907bca1b1b4e89ce32aa982f7261644280
> Sync with ca9e5b9

- src/test-doubles.rst
https://github.com/sebastianbergmann/phpunit-documentation-english/pull/30
> Sync with 09891331

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Sync with https://github.com/sebastianbergmann/phpunit-documentation-english/commit/7965af23def4a84341cf61bc30fe905c44e98fc6
Add CONTRIBUTING.md and use CODE_OF_CONDUCT.md
> Sync with 7965af23

- src/annotations.rst
add a more elaborate description of @testWith
https://github.com/sebastianbergmann/phpunit-documentation-english/commit/e1d3ec261ddd9870a39b8b729b0a655f9b25956f
> Sync with  e1d3ec26

- README.md
https://github.com/sebastianbergmann/phpunit-documentation-english/commit/bc72d5a0f5c94e4f2d60328cf73fd9fd998af91f
add links to translations and documentation on creating a new translation
> Sync with bc72d5a0

- src/annotations.rst
- src/textui.rst
Sync with 4b320beb "add documentation for @ticket annotation"
https://github.com/sebastianbergmann/phpunit-documentation-english/commit/4b320beb8fd3631a8fb0e816d00ffddc6d79300b
> Sync with 4b320beb "add documentation for @ticket annotation"

- src/code-coverage-analysis.rst
See sebastianbergmann/phpunit-documentation-english@84dba20
> Sync 84dba201: Mention the support of PHPDBG

- src/code-coverage-analysis.rst
---> Synchro partielle ---> @@@todo traduction à faire
> branche 7.0 - Synchro partielle pour 4e45f83 - "Closes #42"

- src/configuration.rst
- src/extending-phpunit.rst
synchro : 
-  [x] [0a5f447 -  first draft for doc of extensions added with phpunit#3002](https://github.com/sebastianbergmann/phpunit-documentation-english/commit/0a5f44767b4a2b8e9f8ebcba100fae3fd178191d)
> Synch with 0a5f447 - "first draft for doc of extensions added with phpunit#3002

- src/annotations.rst
synchro en attente pour la branche 7.0 :
2 des 3 modifications sont déjà dans le code source de cette branche
Ne pas fussionner maintenant.
---> consulter : "Synchros à faire" #31
> synchro en attente pour la branche 7.0

- src/test-doubles.rst
synchro en attente pour la branche 7.1 :
Ne pas fussionner maintenant.
---> consulter : "Synchros à faire" #31
> synchro en attente pour la branche 7.1

- src/database.rst
- src/writing-tests-for-phpunit.rst
synchro en attente pour branche master :
Ne pas fussionner maintenant.
---> consulter : "Synchros à faire" #31
> synchro en attente pour branche master

- src/annotations.rst
2 of the 3 modifications are already in the source code.
https://github.com/sebastianbergmann/phpunit-documentation-english/commit/446c41fcc994e025bea2d0e00fca2eeaa9dca096
> Synch with fb461d3c - Merge branch '7.0' into 7.1

- src/writing-tests-for-phpunit.rst
> Sync 8228c98 - "Writing Tests for PHPUnit: various improvements"

- src/test-doubles.rst
- src/writing-tests-for-phpunit.rst
> Sync 9538492 - "fixed rst errors"

- src/code-coverage-analysis.rst
(on addUncoveredFilesFromWhitelist and processUncoveredFilesFromWhitelist usage)
> Add missing translations

- src/annotations.rst
- src/assertions.rst
- src/code-coverage-analysis.rst
- src/logging.rst
- src/test-doubles.rst
copy branch 7.0 updates  (by @l-vo) in the master branch
- #59 Add missing translations
- #58 Fix some french mistakes and small "layout" errors
> copy branch 7.0 updates in the master branch

- src/code-coverage-analysis.rst
partial copy branch 7.0 updates (by @l-vo) in the 7.1 branch 
#59 Add missing translations
> partial copy branch 7.0 updates in the 7.1 branch 

- CONTRIBUTING.md
- README.md
- src/copyright.rst
working PR / please, do not merge it.
> Synchro / WIP

- src/extending-phpunit.rst
> Synch with "75632a - Use finally to simplify example code" / 7.4
